steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package']

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'us-central1-docker.pkg.dev/$PROJECT_ID/blog-repo/blog-app',
      '.'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-central1-docker.pkg.dev/$PROJECT_ID/blog-repo/blog-app'
    ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - blog-backend
      - --image=us-central1-docker.pkg.dev/$PROJECT_ID/blog-repo/blog-app
      - --region=us-central1
      - --platform=managed
      - --allow-unauthenticated
      - --add-cloudsql-instances=money-transfer-frontend:us-central1:blog-db
      # - --set-env-vars=SPRING_PROFILES_ACTIVE=prod
      - --set-env-vars=SPRING_PROFILES_ACTIVE=prod,BUCKET_NAME=blog-images-money-transfer-frontend

images:
  - us-central1-docker.pkg.dev/$PROJECT_ID/blog-repo/blog-app