# spring:
#   application:
#     name: blog

#   datasource:
#     url: jdbc:postgresql:///blog?cloudSqlInstance=money-transfer-frontend:us-central1:blog-db&socketFactory=com.google.cloud.sql.postgres.SocketFactory
#     username: bloguser
#     password: ${DB_PASSWORD}

#   jpa:
#     hibernate:
#       ddl-auto: validate
#     properties:
#       hibernate:
#         dialect: org.hibernate.dialect.PostgreSQLDialect


# server:
#   port: ${PORT:8080}
#   address: 0.0.0.0

spring:
  application:
    name: blog

  datasource:
    # url: jdbc:postgresql://localhost:5432/blog?cloudSqlInstance=money-transfer-frontend:us-central1:blog-db&socketFactory=com.google.cloud.sql.postgres.SocketFactory
    url: jdbc:postgresql:///blog?cloudSqlInstance=money-transfer-frontend:us-central1:blog-db&socketFactory=com.google.cloud.sql.postgres.SocketFactory
    username: bloguser
    password: Postgres.2424

  jpa:
    hibernate:
      ddl-auto: validate

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration


server:
  port: ${PORT:8080}
  address: 0.0.0.0